import Foundation
import CryptoKit

// MARK: - Libre 3 Data Models

/// Represents the cryptographic context for a Libre 3 sensor session
struct Libre3CryptoContext {
    /// Authentication key (kAuth) - stored persistently for returning users
    let kAuth: Data?
    
    /// Encryption key (kEnc) derived from ECDH
    var kEnc: Data?
    
    /// Initialization vector for AES-GCM
    var ivEnc: Data?
    
    /// Sensor PIN (4 bytes)
    let sensorPin: Data
    
    /// Our ECDH private key
    var privateKey: P256.KeyAgreement.PrivateKey?
    
    /// Sensor's ECDH public key
    var sensorPublicKey: P256.KeyAgreement.PublicKey?
    
    /// Current nonce for AES-GCM operations
    var currentNonce: Data?
    
    init(sensorPin: Data, kAuth: Data? = nil) {
        self.sensorPin = sensorPin
        self.kAuth = kAuth
    }
}

/// Represents GATT notification state for Libre 3
struct Libre3NotificationState {
    var patchControlEnabled = false
    var eventLogEnabled = false
    var historicDataEnabled = false
    var clinicalDataEnabled = false
    var factoryDataEnabled = false
    var glucoseDataEnabled = false
    var patchStatusEnabled = false
    var commandResponseEnabled = false
    var certDataEnabled = false
    var challengeDataEnabled = false
    
    /// Returns true if all notifications are enabled
    var allEnabled: Bool {
        return patchControlEnabled &&
               eventLogEnabled &&
               historicDataEnabled &&
               clinicalDataEnabled &&
               factoryDataEnabled &&
               glucoseDataEnabled &&
               patchStatusEnabled &&
               commandResponseEnabled &&
               certDataEnabled &&
               challengeDataEnabled
    }
}

/// Represents a Libre 3 glucose reading
struct Libre3GlucoseReading {
    /// Glucose value in mg/dL
    let glucose: Double
    
    /// Timestamp of the reading
    let timestamp: Date
    
    /// Quality flag
    let quality: UInt8
    
    /// Reading index
    let index: UInt16
}

/// Represents Libre 3 sensor information from NFC
struct Libre3SensorInfo {
    /// Sensor UID (8 bytes)
    let uid: Data
    
    /// Sensor serial number
    let serialNumber: String
    
    /// Sensor activation timestamp
    let activationTime: Date?
    
    /// Sensor warmup duration in minutes
    let warmupDuration: Int
    
    /// Sensor lifetime in minutes
    let lifetime: Int
    
    /// Returns true if this is a Libre 3 sensor (uid.length == 8 && uid[6] != 7)
    var isLibre3: Bool {
        return uid.count == 8 && uid[6] != 7
    }
}

/// Represents the challenge-response data exchange
struct Libre3ChallengeResponse {
    /// r1 from sensor (16 bytes)
    let r1: Data
    
    /// nonce1 from sensor (7 bytes)
    let nonce1: Data
    
    /// r2 generated by us (16 bytes)
    let r2: Data
    
    /// Combined data for encryption
    var combinedData: Data {
        var data = Data()
        data.append(r1)
        data.append(r2)
        data.append(contentsOf: [0x00, 0x00]) // padding
        return data
    }
}

/// Represents patch status information
struct Libre3PatchStatus {
    /// Sensor age in minutes
    let sensorAge: Int
    
    /// Battery percentage
    let batteryPercentage: Int
    
    /// Temperature in Celsius
    let temperature: Double
    
    /// Status flags
    let statusFlags: UInt16
}

/// GATT characteristic identifiers for Libre 3
enum Libre3Characteristic: String, CaseIterable {
    case commandResponse = "F002"
    case challengeData = "F003"
    case certData = "F004"
    case glucoseData = "F005"
    case historicData = "F006"
    case clinicalData = "F007"
    case factoryData = "F008"
    case patchStatus = "F009"
    case patchControl = "F00A"
    case eventLog = "F00B"
    
    /// The order in which notifications should be enabled
    static let notificationOrder: [Libre3Characteristic] = [
        .patchControl,
        .eventLog,
        .historicData,
        .clinicalData,
        .factoryData,
        .glucoseData,
        .patchStatus,
        .commandResponse,
        .certData,
        .challengeData
    ]
}

/// LibreView upload payload structure
struct Libre3LibreViewPayload: Codable {
    let deviceData: DeviceData
    let userToken: String
    let domain: String
    let gatewayType: String
    
    struct DeviceData: Codable {
        let deviceSettings: DeviceSettings
        let header: Header
        let measurementLog: MeasurementLog
        
        struct DeviceSettings: Codable {
            let systemTimeOffset: Int
            let dateTime: String
        }
        
        struct Header: Codable {
            let device: Device
            
            struct Device: Codable {
                let hardwareDescriptor: String
                let osType: String
                let osVersion: String
                let uniqueIdentifier: String
            }
        }
        
        struct MeasurementLog: Codable {
            let currentGlucoseEntries: [GlucoseEntry]
            let scheduledContinuousGlucoseEntries: [GlucoseEntry]
            let foodEntries: [FoodEntry]
            let insulinEntries: [InsulinEntry]
            
            struct GlucoseEntry: Codable {
                let timestamp: String
                let value: Double
                let quality: Int
            }
            
            struct FoodEntry: Codable {
                // Empty for now
            }
            
            struct InsulinEntry: Codable {
                // Empty for now
            }
        }
    }
    
    enum CodingKeys: String, CodingKey {
        case deviceData = "DeviceData"
        case userToken = "UserToken"
        case domain = "Domain"
        case gatewayType = "GatewayType"
    }
}
